# Generated by Django 5.1.3 on 2024-11-22 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_filecomment_attachment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filecomment',
            name='attachment',
        ),
        migrations.AddField(
            model_name='filecomment',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='users.task', verbose_name='Задача'),
        ),
        migrations.AlterField(
            model_name='taskattachment',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='users.task', verbose_name='Задача'),
        ),
    ]
